---
- name: "Manage Cloudflare DNS record"
  hosts: localhost
  tasks:
    - name: "Update DNS record"
      cloudflare_dns:
        api_token: "{{ cloudflare_tokens[account] }}"
        zone: "{{ zone }}"
        record: "{{ record }}"
        type: "A"
        value: "{{ hostvars[host].ansible_host }}"
        proxied: yes
        solo: yes
      delegate_to: localhost
 