---
- name: FirewallD - Enable service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: FirewallD - Enable SSH
  ansible.posix.firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: FirewallD - Enable NGINX ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
  loop: "{{ nginx_confs.ports }}"
  when: nginx_confs.ports is defined
