---
- name: Install deployment dependencies
  hosts: all
  become: yes
  tasks:
    - name: Include vars
      include_tasks: ../tasks/include_vars.yml
    - name: FirewallD
      include_tasks: ../tasks/firewall.yml