---
- name: Setup NGINX config
  hosts: all
  become: yes  
  tasks:
    - name: Include vars
      include_tasks: ../tasks/include_vars.yml
    - name: Setup NGINX config
      include_role: 
        name: rock-n-block.nginx-role
