---
- name: FirewallD - Enable service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: FirewallD - Enable SSH
  ansible.posix.firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: FirewallD - Enable NGINX ports
  ansible.posix.firewalld:
    port: "{{ item.port }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ nginx_confs.values() }}"
  when: nginx_confs.ports is defined

- name: FirewallD - Enable ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ ports }}"
  when: ports is defined

