---
- name: Install deployment dependencies
  hosts: all
  become: yes
  tasks:
    - name: Include vars
      include_tasks: ../tasks/include_vars.yml
    - name: Update package cache
      block:
        - name: Update package cache (apt/Ubuntu)
          apt:
            update_cache: yes
          when: ansible_distribution == "Ubuntu"
        - name: Update package cache (dnf/CentOS)
          dnf:
            update_cache: yes
          when: ansible_distribution == "CentOS"
        - name: Update package cache (yum/Amazon)
          yum:
            update_cache: yes
          when: ansible_distribution == "Amazon"
    - name: install package dependencies
      package: name={{ item }} state=present
      with_items: "{{ packages|default(default_packages) }}"
    - name: Enable NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes
      when: "'nginx' in packages|default(default_packages)"
    - name: Install Docker & docker-compose
      include_role:
        name: rock-n-block.docker-role
      when: "'docker' in deps|default(default_deps)"
    - name: FirewallD
      include_tasks: ../tasks/firewall.yml
      when: "'firewalld' in packages|default(default_packages)"
    