---

- name: Deploy ssh keys
  hosts: all
  become: yes
  vars:
    username: "{{ username }}"
  
  tasks:
  - name: Include vars
    include_tasks: ../tasks/include_vars.yml

  - name: Get ssh keys
    uri:
      url: "{{ssh_url}}{{ username }}"
    register: response

  - name:
    ansible.builtin.group:
      name: "{{ item.user.role }}"
      state: present
    loop: "{{ response.json }}"
    when: response.json is defined

  - name:
    user:
      name: "{{ item.user.role }}"
      shell: /bin/bash
      group: "{{ item.user.role }}"
      groups:
        - "{{ item.user.role }}"
        - "{{ 'sudo' if item.user.role in ['backend', 'devops'] else '' }}"
    loop: "{{ response.json }}"
    when: response.json is defined

  - name: Insert a line at the end of a file.
    lineinfile:
      path: "/etc/sudoers"
      line: "{{ item.user.role }} ALL=(ALL) NOPASSWD: ALL"
    loop: "{{ response.json }}"
    when: (response.json is defined and item.user.role in ['backend', 'devops'])

  - name: mkdir
    file:
      path: "/home/{{ item.user.role }}/.ssh"
      state: directory
      mode: 0700
      owner: "{{ item.user.role }}"
    loop: "{{ response.json }}"
    when: response.json is defined

  - name: touch
    file:
      path: "/home/{{ item.user.role }}/.ssh/authorized_keys"
      state: touch
      mode: 0600
      owner: "{{ item.user.role }}"
    loop: "{{ response.json }}"
    when: response.json is defined

  - name: Insert a line at the end of a file.
    lineinfile:
      path: "/home/{{ item.user.role }}/.ssh/authorized_keys"
      line: "{{ item.pub }}"
    loop: "{{ response.json }}"
    when: response.json is defined